const Mockdata = [
    {
        "snumber": "000",
        "schoolid": "15",
        "sname": "San Felipe Del Rio Consolidated Independent School District",
        "scategory": "District",
        "principal": ",",
        "grades": "EE-12",
        "enrollment": "10515",
        "scode": "233901000",
        "itype": "Regular Instructional",
        "address": "205 Memorial Drive",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4000",
        "fax": "(830) 774-9892",
        "email": "carlos.rios@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org",
        "lowgrade": "EE",
        "highgrade": "12",
        "latitude": "29.384612",
        "principallastname": "",
        "principalmiddlename": "",
        "principalfirstname": "",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.916462",
        "principalemail": "",
        "enabled": true,
        "comments": "",
        "creationdate": "3/16/2017 1:03:29 AM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "3/16/2017 1:03:29 AM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "001",
        "schoolid": "1",
        "sname": "Del Rio High School",
        "scategory": "High School",
        "principal": "Dr. Jose,Perez",
        "grades": "10-12",
        "enrollment": "2181",
        "scode": "233901001",
        "itype": "Regular Instructional",
        "address": "100 Memorial Drive",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4300",
        "fax": "(830) 774-9320",
        "email": "Jose.Perez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/high-school/del-rio-high-school/",
        "lowgrade": "10",
        "highgrade": "12",
        "latitude": "29.383694",
        "principallastname": "Perez",
        "principalmiddlename": "",
        "principalfirstname": "Dr. Jose",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.917048",
        "principalemail": "Jose.Perez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 4:41:28 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 4:41:28 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\001\\001_DelRio_High_school.png",
        "rating": "Improvement Required",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "001",
        "schoolid": "1",
        "sname": "Del Rio High School",
        "scategory": "High School",
        "principal": "Dr. Jose,Perez",
        "grades": "10-12",
        "enrollment": "2181",
        "scode": "233901001",
        "itype": "Regular Instructional",
        "address": "100 Memorial Drive",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4300",
        "fax": "(830) 774-9320",
        "email": "Jose.Perez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/high-school/del-rio-high-school/",
        "lowgrade": "10",
        "highgrade": "12",
        "latitude": "29.383694",
        "principallastname": "Perez",
        "principalmiddlename": "",
        "principalfirstname": "Dr. Jose",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.917048",
        "principalemail": "Jose.Perez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 4:41:28 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 4:41:28 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\001\\001_DelRio_High_school.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "002",
        "schoolid": "2",
        "sname": "Del Rio Freshman School",
        "scategory": "Freshman School",
        "principal": "Thomas,Cabello",
        "grades": "9-9",
        "enrollment": "749",
        "scode": "233901002",
        "itype": "Regular Instructional",
        "address": "90 Memorial Drive",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4400",
        "fax": "(830) 774-9873",
        "email": "thomas.cabello@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/high-school/del-rio-freshman-school/",
        "lowgrade": "9",
        "highgrade": "9",
        "latitude": "29.384577",
        "principallastname": "Cabello",
        "principalmiddlename": "",
        "principalfirstname": "Thomas",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.916402",
        "principalemail": "thomas.cabello@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:00:22 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:00:22 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\002\\002_Del_Rio_FreshmanSchool.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "004",
        "schoolid": "3",
        "sname": "Blended Academy",
        "scategory": "Alternative School",
        "principal": "Jose,Rodriguez",
        "grades": "8-12",
        "enrollment": "63",
        "scode": "233901004",
        "itype": "Alternative Instructional",
        "address": "305 Las Vacas St",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4680",
        "fax": "(830) 774-9960",
        "email": "jose.rodriguez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/high-school/blended-academy/",
        "lowgrade": "8",
        "highgrade": "12",
        "latitude": "29.357775",
        "principallastname": "Rodriguez",
        "principalmiddlename": "",
        "principalfirstname": "Jose",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.902462",
        "principalemail": "jose.rodriguez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:13:04 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:13:04 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\004\\004_BlendedAcademy.jpg",
        "rating": "Improvement Required",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "004",
        "schoolid": "3",
        "sname": "Blended Academy",
        "scategory": "Alternative School",
        "principal": "Jose,Rodriguez",
        "grades": "8-12",
        "enrollment": "63",
        "scode": "233901004",
        "itype": "Alternative Instructional",
        "address": "305 Las Vacas St",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4680",
        "fax": "(830) 774-9960",
        "email": "jose.rodriguez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/high-school/blended-academy/",
        "lowgrade": "8",
        "highgrade": "12",
        "latitude": "29.357775",
        "principallastname": "Rodriguez",
        "principalmiddlename": "",
        "principalfirstname": "Jose",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.902462",
        "principalemail": "jose.rodriguez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:13:04 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:13:04 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\004\\004_BlendedAcademy.jpg",
        "rating": "Met Alternative Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "005",
        "schoolid": "16",
        "sname": "Del Rio Early College High School",
        "scategory": "High School",
        "principal": "Patricia,Rodriguez",
        "grades": "9-12",
        "enrollment": "",
        "scode": "233901005",
        "itype": "Regular Instructional",
        "address": "100 MEMORIAL DR",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4416",
        "fax": "(830) 774-9873",
        "email": "Patricia.Rodriguez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/high-school/early-college-high-school/",
        "lowgrade": "9",
        "highgrade": "12",
        "latitude": "29.383694",
        "principallastname": "Rodriguez",
        "principalmiddlename": "",
        "principalfirstname": "Patricia",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.917048",
        "principalemail": "Patricia.Rodriguez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "8/13/2017 12:53:31 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "8/13/2017 12:53:31 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\005\\005_EarlyCollege_High_school.png",
        "rating": "",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "043",
        "schoolid": "4",
        "sname": "Del Rio Middle School",
        "scategory": "Middle School",
        "principal": "Sergio,Jimenez",
        "grades": "7-8",
        "enrollment": "1535",
        "scode": "233901043",
        "itype": "Regular Instructional",
        "address": "720 Raymond Lozano Blvd",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4500",
        "fax": "(830) 778-4912",
        "email": "sergio.jimenez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/middle-school/del-rio-middle-school/",
        "lowgrade": "7",
        "highgrade": "8",
        "latitude": "29.375327103000075",
        "principallastname": "Jimenez",
        "principalmiddlename": "",
        "principalfirstname": "Sergio",
        "schoolstatus": "Active",
        "zip": "78842",
        "longitude": "-100.876752263999947",
        "principalemail": "sergio.jimenez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:22:58 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:22:58 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\043\\043_Del_Rio_Middle_School.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "102",
        "schoolid": "5",
        "sname": "Garfield Elementary",
        "scategory": "Elementary School",
        "principal": "Genella,Rubio",
        "grades": "KG-6",
        "enrollment": "700",
        "scode": "233901102",
        "itype": "Regular Instructional",
        "address": "300 W Martin St",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4700",
        "fax": "(830) 774-9928",
        "email": "genella.rubio@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/garfield-elementary/",
        "lowgrade": "KG",
        "highgrade": "6",
        "latitude": "29.360457",
        "principallastname": "Rubio",
        "principalmiddlename": "",
        "principalfirstname": "Genella",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.901831",
        "principalemail": "genella.rubio@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:38:05 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:38:05 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\102\\102_Garfiled_elementary_school.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "103",
        "schoolid": "6",
        "sname": "North Heights Elementary",
        "scategory": "Elementary School",
        "principal": "Maytte,Soliz",
        "grades": "EE-8",
        "enrollment": "727",
        "scode": "233901103",
        "itype": "Regular Instructional",
        "address": "2003 N. Main St",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4777",
        "fax": "(830) 778-4922",
        "email": "maytte.soliz@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/north-heights-elementary/",
        "lowgrade": "EE",
        "highgrade": "8",
        "latitude": "29.381204",
        "principallastname": "Soliz",
        "principalmiddlename": "",
        "principalfirstname": "Maytte",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.910964",
        "principalemail": "maytte.soliz@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:47:43 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:47:43 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\103\\103_North_Heights_elementary.png",
        "rating": "Improvement Required",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "103",
        "schoolid": "6",
        "sname": "North Heights Elementary",
        "scategory": "Elementary School",
        "principal": "Maytte,Soliz",
        "grades": "EE-8",
        "enrollment": "727",
        "scode": "233901103",
        "itype": "Regular Instructional",
        "address": "2003 N. Main St",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4777",
        "fax": "(830) 778-4922",
        "email": "maytte.soliz@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/north-heights-elementary/",
        "lowgrade": "EE",
        "highgrade": "8",
        "latitude": "29.381204",
        "principallastname": "Soliz",
        "principalmiddlename": "",
        "principalfirstname": "Maytte",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.910964",
        "principalemail": "maytte.soliz@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:47:43 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:47:43 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\103\\103_North_Heights_elementary.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "104",
        "schoolid": "7",
        "sname": "San Felipe Memorial Middle School",
        "scategory": "Middle School",
        "principal": "Dr. Celia,Zuniga-Barrera",
        "grades": "6-6",
        "enrollment": "771",
        "scode": "233901104",
        "itype": "Regular Instructional",
        "address": "1207 West Garza Street",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4570",
        "fax": "(830) 778-4920",
        "email": "celia.zuniga-barrera@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/middle-school/san-felipe-memorial-middle-school/",
        "lowgrade": "6",
        "highgrade": "6",
        "latitude": "29.357928",
        "principallastname": "Zuniga-Barrera",
        "principalmiddlename": "",
        "principalfirstname": "Dr. Celia",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.881419",
        "principalemail": "celia.zuniga-barrera@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:58:23 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:58:23 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\104\\104_1_SanFelipeMemorialMiddle_School.png",
        "rating": "Improvement Required",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "104",
        "schoolid": "7",
        "sname": "San Felipe Memorial Middle School",
        "scategory": "Middle School",
        "principal": "Dr. Celia,Zuniga-Barrera",
        "grades": "6-6",
        "enrollment": "771",
        "scode": "233901104",
        "itype": "Regular Instructional",
        "address": "1207 West Garza Street",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4570",
        "fax": "(830) 778-4920",
        "email": "celia.zuniga-barrera@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/middle-school/san-felipe-memorial-middle-school/",
        "lowgrade": "6",
        "highgrade": "6",
        "latitude": "29.357928",
        "principallastname": "Zuniga-Barrera",
        "principalmiddlename": "",
        "principalfirstname": "Dr. Celia",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.881419",
        "principalemail": "celia.zuniga-barrera@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 5:58:23 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 5:58:23 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\104\\104_1_SanFelipeMemorialMiddle_School.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "106",
        "schoolid": "8",
        "sname": "Lamar Elementary",
        "scategory": "Elementary School",
        "principal": "Maryvel,Flores",
        "grades": "KG-5",
        "enrollment": "586",
        "scode": "233901106",
        "itype": "Regular Instructional",
        "address": "301 Waters Ave",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4730",
        "fax": "(830) 774-9493",
        "email": "maryvel.flores@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/lamar-elementary/",
        "lowgrade": "KG",
        "highgrade": "5",
        "latitude": "29.361420",
        "principallastname": "Flores",
        "principalmiddlename": "",
        "principalfirstname": "Maryvel",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.884648",
        "principalemail": "maryvel.flores@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:04:46 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:04:46 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\106\\106_1_Lamar_Elementary.png",
        "rating": "Improvement Required",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "106",
        "schoolid": "8",
        "sname": "Lamar Elementary",
        "scategory": "Elementary School",
        "principal": "Maryvel,Flores",
        "grades": "KG-5",
        "enrollment": "586",
        "scode": "233901106",
        "itype": "Regular Instructional",
        "address": "301 Waters Ave",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4730",
        "fax": "(830) 774-9493",
        "email": "maryvel.flores@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/lamar-elementary/",
        "lowgrade": "KG",
        "highgrade": "5",
        "latitude": "29.361420",
        "principallastname": "Flores",
        "principalmiddlename": "",
        "principalfirstname": "Maryvel",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.884648",
        "principalemail": "maryvel.flores@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:04:46 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:04:46 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\106\\106_1_Lamar_Elementary.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "108",
        "schoolid": "9",
        "sname": "Irene C. Cardwell Elementary",
        "scategory": "Elementary School",
        "principal": "Rufina,Adams",
        "grades": "EE-PK",
        "enrollment": "506",
        "scode": "233901108",
        "itype": "Regular Instructional",
        "address": "1009 Ave. J",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4650",
        "fax": "(830) 774-9855",
        "email": "rufina.adams@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/irene-c-cardwell-elementary/",
        "lowgrade": "EE",
        "highgrade": "PK",
        "latitude": "29.374702",
        "principallastname": "Adams",
        "principalmiddlename": "",
        "principalfirstname": "Rufina",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.897095",
        "principalemail": "rufina.adams@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:11:44 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:11:44 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\108\\108_1_Irene C.CardwellElementary.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "110",
        "schoolid": "10",
        "sname": "Buena Vista Elementary",
        "scategory": "Elementary School",
        "principal": "Jennifer,Sutton",
        "grades": "KG-05",
        "enrollment": "695",
        "scode": "233901110",
        "itype": "Regular Instructional",
        "address": "100 Echo Valley Dr",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4600",
        "fax": "(830) 774-9875",
        "email": "jennifer.sutton@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/buena-vista-elementary/",
        "lowgrade": "KG",
        "highgrade": "05",
        "latitude": "29.406700",
        "principallastname": "Sutton",
        "principalmiddlename": "",
        "principalfirstname": "Jennifer",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.919356",
        "principalemail": "jennifer.sutton@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:18:27 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:18:27 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\110\\110_1_BuenaVistaElementary.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "111",
        "schoolid": "11",
        "sname": "Ruben Chavira Elementary",
        "scategory": "Elementary School",
        "principal": "Maria,Correa",
        "grades": "KG-05",
        "enrollment": "586",
        "scode": "233901111",
        "itype": "Regular Instructional",
        "address": "2253 U.S. 277",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4660",
        "fax": "(830) 778-4921",
        "email": "maria.correa@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/ruben-chavira-elementary/",
        "lowgrade": "KG",
        "highgrade": "05",
        "latitude": "29.917933",
        "principallastname": "Correa",
        "principalmiddlename": "",
        "principalfirstname": "Maria",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.77408",
        "principalemail": "maria.correa@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:24:26 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:24:26 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\111\\111_1_Ruben_Chavira_Elementary.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "112",
        "schoolid": "12",
        "sname": "Dr. Fermin Calderon Elementary",
        "scategory": "Elementary School",
        "principal": "Jane,Villarreal",
        "grades": "EE-12",
        "enrollment": "661",
        "scode": "233901112",
        "itype": "Regular Instructional",
        "address": "1900 HWY 90 E",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4620",
        "fax": "(830) 774-9975",
        "email": "jane.villarreal@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/dr-fermin-calderon-elementary/",
        "lowgrade": "EE",
        "highgrade": "12",
        "latitude": "29.449469",
        "principallastname": "Villarreal",
        "principalmiddlename": "",
        "principalfirstname": "Jane",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.926657",
        "principalemail": "jane.villarreal@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:31:25 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:31:25 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\112\\112_1_dr_fermin_calderon_elementary.jpg",
        "rating": "Improvement Required",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "112",
        "schoolid": "12",
        "sname": "Dr. Fermin Calderon Elementary",
        "scategory": "Elementary School",
        "principal": "Jane,Villarreal",
        "grades": "EE-12",
        "enrollment": "661",
        "scode": "233901112",
        "itype": "Regular Instructional",
        "address": "1900 HWY 90 E",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4620",
        "fax": "(830) 774-9975",
        "email": "jane.villarreal@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/dr-fermin-calderon-elementary/",
        "lowgrade": "EE",
        "highgrade": "12",
        "latitude": "29.449469",
        "principallastname": "Villarreal",
        "principalmiddlename": "",
        "principalfirstname": "Jane",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.926657",
        "principalemail": "jane.villarreal@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:31:25 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:31:25 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\112\\112_1_dr_fermin_calderon_elementary.jpg",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "113",
        "schoolid": "13",
        "sname": "Dr. Lonnie Green Elementary",
        "scategory": "Elementary School",
        "principal": "Cheryl,Pond",
        "grades": "EE-5",
        "enrollment": "755",
        "scode": "233901113",
        "itype": "Regular Instructional",
        "address": "905 Cantu Road",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4750",
        "fax": "(830) 774-9532",
        "email": "cheryl.pond@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/dr-lonnie-green-elementary/",
        "lowgrade": "EE",
        "highgrade": "5",
        "latitude": "29.387154",
        "principallastname": "Pond",
        "principalmiddlename": "",
        "principalfirstname": "Cheryl",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.925066",
        "principalemail": "cheryl.pond@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:37:08 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:37:08 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\113\\113_1_dr_Lonnie_Green_Elementary.png",
        "rating": "Met Standard",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "114",
        "schoolid": "18",
        "sname": "Laughlin Elementary STEM Magnet",
        "scategory": "Elementary School",
        "principal": "Libana,Milender",
        "grades": "KG-05",
        "enrollment": "0",
        "scode": "233901114",
        "itype": "STEM Magnet School",
        "address": "427 Liberty Drive",
        "city": "Laughlin AFB",
        "state": "TX",
        "phone": "(830) 778-4570",
        "fax": "(830) 778-4570",
        "email": "Libana.Milender@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/elementary-school/laughlin-elementary-stem-magnet/",
        "lowgrade": "KG",
        "highgrade": "05",
        "latitude": "29.356558",
        "principallastname": "Milender",
        "principalmiddlename": "",
        "principalfirstname": "Libana",
        "schoolstatus": "Active",
        "zip": "78843",
        "longitude": "-100.783083",
        "principalemail": "Libana.Milender@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "6/10/2018 4:02:11 AM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "6/10/2018 4:02:11 AM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\1\\images\\school\\114\\114_1_Laughlin_STEM_Magnet_Elementary.png",
        "rating": "",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "119",
        "schoolid": "14",
        "sname": "Juvenile Detention Center",
        "scategory": "Alternative School",
        "principal": " , ",
        "grades": "6-12",
        "enrollment": "0",
        "scode": "233901119",
        "itype": "JJAEP Instructional",
        "address": "PO BOX 420128",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4450",
        "fax": "(830) 778-4905",
        "email": "ramon.menchaca@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org",
        "lowgrade": "6",
        "highgrade": "12",
        "latitude": "",
        "principallastname": " ",
        "principalmiddlename": "",
        "principalfirstname": " ",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "",
        "principalemail": " ",
        "enabled": true,
        "comments": "",
        "creationdate": "7/2/2016 6:48:26 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "7/2/2016 6:48:26 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\",
        "rating": "",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "200",
        "schoolid": "17",
        "sname": "Student Guidance and Learning Center",
        "scategory": "Alternative School",
        "principal": "Brian,Westlake",
        "grades": "1-12",
        "enrollment": "",
        "scode": "233901200",
        "itype": "Alternative Instructional",
        "address": "305 Las Vacas St",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4680",
        "fax": "(830) 774-9960",
        "email": "brian.westlake@sfdr-cisd.org",
        "web": "http://www.sfdr-cisd.org/alternative-school/sglc/",
        "lowgrade": "1",
        "highgrade": "12",
        "latitude": "29.357775",
        "principallastname": "Westlake",
        "principalmiddlename": "",
        "principalfirstname": "Brian",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.902462",
        "principalemail": "brian.westlake@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "8/23/2017 2:19:19 AM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "8/23/2017 2:19:19 AM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\",
        "rating": "",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00"
    },
    {
        "snumber": "300",
        "schoolid": "20",
        "sname": "Career and Technical Education",
        "scategory": "Alternative School",
        "principal": "Roger,Gonzalez",
        "grades": "6-12",
        "enrollment": "",
        "scode": "233901300",
        "itype": "Alternative Instructional",
        "address": "201 E. 10th Street",
        "city": "Del Rio",
        "state": "TX",
        "phone": "(830) 778-4368",
        "fax": "(830) 774-9320",
        "email": "roger.gonzalez@sfdr-cisd.org",
        "web": "www.sfdr-cisd.org/alternative-school/career-and-technical-education/",
        "lowgrade": "6",
        "highgrade": "12",
        "latitude": "29.373790",
        "principallastname": "Gonzalez",
        "principalmiddlename": "",
        "principalfirstname": "Roger",
        "schoolstatus": "Active",
        "zip": "78840",
        "longitude": "-100.905209",
        "principalemail": "roger.gonzalez@sfdr-cisd.org",
        "enabled": true,
        "comments": "",
        "creationdate": "6/17/2018 6:35:45 PM",
        "createdby": "Medixsoft Inc.",
        "lastupdatedate": "6/17/2018 6:35:45 PM",
        "lastupdatedby": "Medixsoft Inc.",
        "imagepath": "http://ec2-34-209-104-196.us-west-2.compute.amazonaws.com:9090\\",
        "rating": "",
        "accountId": 0,
        "applicationId": 0,
        "applicationTabId": 0,
        "CreateDateTime": "0001-01-01T00:00:00",
        "UpdateDateTime": "0001-01-01T00:00:00",
    }
];
export default Mockdata;
//# sourceMappingURL=Mockdata.js.map