import * as React from "react";
import { Row, Col, Text } from "native-base";
import Icon from "react-native-vector-icons/FontAwesome";
import { View, TouchableHighlight } from "react-native";
class GridNavigation extends React.Component {
    render() {
        const styles = {
            gridIcon: {
                fontSize: 28,
                color: "#27ae60",
            },
        };
        const param = this.props.navigation.state.params;
        return (React.createElement(View, null,
            React.createElement(Row, { style: { marginBottom: 10, marginTop: 10 } },
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("RatingPage"); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "star" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Ratings")))),
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("Kpi"); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "bar-chart" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "KPI")))),
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => this.props.navigation.navigate("SearchPage", Object.assign({ name: "SearchPage" }, param)) },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "university" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Schools"))))),
            React.createElement(Row, { style: { marginBottom: 10, marginTop: 10 } },
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("TrusteesListPage"); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "user-circle" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Trustee")))),
                React.createElement(Col, null,
                    React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                        React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "cogs" }),
                        React.createElement(Text, { style: { marginTop: 5 } }, "Admin"))),
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("GMaps"); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "map" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Maps"))))),
            React.createElement(Row, { style: { marginBottom: 10, marginTop: 10 } },
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("NewsPage"); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "rss" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "News")))),
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("Calendar", Object.assign({}, param)); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "calendar" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Calendar")))),
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("ContactPage", Object.assign({}, param)); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "phone" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Contact"))))),
            React.createElement(Row, null,
                React.createElement(Col, null,
                    React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                        React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "user" }),
                        React.createElement(Text, { style: { marginTop: 5 } }, "Student"))),
                React.createElement(Col, null,
                    React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                        React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "users" }),
                        React.createElement(Text, { style: { marginTop: 5 } }, "Parent"))),
                React.createElement(Col, null,
                    React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                        React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "home" }),
                        React.createElement(Text, { style: { marginTop: 5 } }, "Employee")))),
            React.createElement(Row, { style: { marginBottom: 10, marginTop: 10 } },
                React.createElement(Col, null,
                    React.createElement(TouchableHighlight, { onPress: () => { this.props.navigation.navigate("TrasnportPage", Object.assign({}, param)); } },
                        React.createElement(View, { style: { alignItems: "center", padding: 5 } },
                            React.createElement(Icon, { size: styles.gridIcon.fontSize, color: styles.gridIcon.color, name: "bus" }),
                            React.createElement(Text, { style: { marginTop: 5 } }, "Bus Tracking")))),
                React.createElement(Col, null),
                React.createElement(Col, null))));
    }
}
export default GridNavigation;
//# sourceMappingURL=index.js.map