import * as React from "react";
import { Container, Header, Title, Content, Text, Button, Icon, Left, Right, Body, List, ListItem, Thumbnail } from "native-base";
import styles from "./styles";
class NewsPage extends React.Component {
    render() {
        const param = this.props.navigation.state.params;
        return (React.createElement(Container, { style: styles.container },
            React.createElement(Header, null,
                React.createElement(Left, null,
                    React.createElement(Button, { transparent: true, onPress: () => this.props.navigation.goBack() },
                        React.createElement(Icon, { name: "ios-arrow-back" }))),
                React.createElement(Body, { style: { flex: 3 } },
                    React.createElement(Title, null, param ? param.name : "News Page")),
                React.createElement(Right, null)),
            React.createElement(Content, { padder: true },
                React.createElement(List, null,
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "DRFS"),
                            React.createElement(Text, { note: true }, "Addressing a rally in Jalandhar Modi sought support fro Pakistan Sing Badal of the running SAD, urging people to vot him in for a third state firm"))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "SFDR-CISD"),
                            React.createElement(Text, { note: true }, "The 2014 Poll manifesto of the BJP promised to provide non-adversarial pentagon ,the US President said .and consuctive tac environment and rationalization and simplification of tax"))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "DRHS"),
                            React.createElement(Text, { note: true }, "We will never forget the lessons of 9/11 nor the Heros who lost at the"))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "Gae-Building"),
                            React.createElement(Text, { note: true }, "Very soon ,Donald Trump us expexted to sign an executive order regarding refuces and entry to the US for a whole swathe of people."))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "Lamar"),
                            React.createElement(Text, { note: true }, "Apple has released the public betea if its lastest IOS update , giving us a glimse of the new features coming to its iphone ,ipads and ipods"))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "NHES"),
                            React.createElement(Text, { note: true }, "Addressing a rally in Jalandhar Modi sought support fro Pakistan Sing Badal of the running SAD, urging people to vot him in for a third state firm"))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "DRFS"),
                            React.createElement(Text, { note: true }, "The 2014 Poll manifesto of the BJP promised to provide non-adversarial pentagon ,the US President said .and consuctive tac environment and rationalization and simplification of tax"))),
                    React.createElement(ListItem, { avatar: true },
                        React.createElement(Left, null,
                            React.createElement(Thumbnail, { square: true, source: { uri: "https://upload.wikimedia.org/wikipedia/commons/5/5f/Larkmead_School%2C_Abingdon%2C_Oxfordshire.png" } })),
                        React.createElement(Body, null,
                            React.createElement(Text, null, "SFDR-Poll CISD"),
                            React.createElement(Text, { note: true }, "The 2014 Poll manifesto of the BJP promised to provide non-adversarial pentagon ,the US President said .and consuctive tac environment and rationalization and simplification of tax\"")))))));
    }
}
export default NewsPage;
//# sourceMappingURL=index.js.map